# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatable',
            name='image',
            field=models.ImageField(default='', upload_to='Images/'),
        ),
    ]
